apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-acr
  labels:
    app: nginx-hello-acr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-acr
  template:
    metadata:
      labels:
        app: nginx-hello-acr
    spec:
      containers:
      - name: nginx
        image: variantcourselabsacr.azurecr.io/excercises-jonas-0-test-0-1-dockerbuild:162278848f10c931380e274a80fdd1f3c0b70b55
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-acr-svc
spec:
  selector:
    app: nginx-hello-acr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-acr-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-lab

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - template.course.variant.dev
    secretName: nginx-hello-acr-tls
  rules:
    - host: jonas-docker.course.variant.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-hello-acr-svc
              port:
                number: 80