apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-acr
  labels:
    app: nginx-hello-acr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-acr
  template:
    metadata:
      labels:
        app: nginx-hello-acr
    spec:
      containers:
      - name: nginx
        image: variantcourselabsacr.azurecr.io/excercises-jonas-0-test-0-1-dockerbuild:05f1469e1b6d08a9fbf4d13c35ce3d378e722dca
        ports:
        - containerPort: 8080
        environment:
         - name: FAV_LUNCH
           value: "pizza"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-acr-svc
spec:
  selector:
    app: nginx-hello-acr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-acr-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-lab

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jonas-docker.course.variant.dev
    secretName: nginx-hello-acr-tls
  rules:
    - host: jonas-docker.course.variant.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-hello-acr-svc
              port:
                number: 80