apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: variantcourselabsacr.azurecr.io/excercises-kjetil-0-test-0-1-dockerbuild:6beb162a1303b75bd659a07539ee5e116abb1078
          ports:
            - containerPort: 80
          env:
            - name: FAV_LUNCH
              value: "Siljbalj!!"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-lab

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kjetil-docker.course.variant.dev
      secretName: my-app-tls
  rules:
    - host: kjetil-docker.course.variant.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-svc
                port:
                  number: 80
