apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: variantcourselabsacr.azurecr.io/excercises-morten-0-1-dockerbuild:898b1c0b6e838d3a48918cbc3786d2a167e76c0a
        ports:
        - containerPort: 8080
        env:
        - name: FAV_LUNCH
          value: "Pizza"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-lab

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - morten.course.variant.dev
    secretName: my-app-tls
  rules:
    - host: morten.course.variant.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-app-svc
              port:
                number: 80